version: "3.10"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: 
      - environments/postgresql.env
    ports:
      - "5432:5432"
    expose:
      - 5432
  web:
    build: .
    command: python main.py
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: 
      - environments/postgresql.env